version: "3.9"

services:
    api:
        build: .
        restart: always
        ports:
            -   "8080:80"
        volumes:
            -   ./:/var/www/html
            -   ./docker/volumes/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            -   db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            -   "5432:5432"
        volumes:
            -   ./docker/volumes/db/data:/var/lib/postgresql/data
